export const GET_PRODUCTS_PENDING = "GET_PRODUCTS_PENDING";
export const GET_PRODUCTS_FULFILLED = "GET_PRODUCTS_FULFILLED";
export const GET_PRODUCTS_REJECTED = "GET_PRODUCTS_REJECTED";
export const GET_PRODUCTS_ATTR_CHANGED = "GET_PRODUCTS_ATTR_CHANGED";
export const PER_PAGE_PRODUCTS = 5;
