// SEND_OTP
export const SEND_OTP_PENDING = "SEND_OTP_PENDING";
export const SEND_OTP_FULFILLED = "SEND_OTP_FULFILLED";
export const SEND_OTP_REJECTED = "SEND_OTP_REJECTED";
export const OTP_CHANGED = "OTP_CHANGED";
