// Signup
export const SIGNUP_PENDING = "SIGNUP_PENDING";
export const SIGNUP_FULFILLED = "SIGNUP_FULFILLED";
export const SIGNUP_REJECTED = "SIGNUP_REJECTED";
export const PHONE_CHANGED = "PHONE_CHANGED";
export const ORG_NAME_CHANGED = "ORG_NAME_CHANGED";
export const DOMAIN_NAME_CHANGED = "DOMAIN_NAME_CHANGED";
export const SIGNUP_FORM_CHANGED = "SIGNUP_FORM_CHANGED";
export const SIGNUP_VALIDATION = "SIGNUP_VALIDATION";
export const LANDMARK_TYPE_CHANGED = "LANDMARK_TYPE_CHANGED";
